# Netlify configuration for SpeakFlow web app
[build]
  command = "cd mobile && NODE_ENV=production npx expo export --platform web && cd .. && cp -r mobile/dist/* ."
  publish = "."

# SPA redirect for React Navigation
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance
[[headers]]
  for = "/_expo/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
