[build]
  # Let Railway use the default npm install in root
  
[deploy]
  # Start command for the backend
  startCommand = "npm start"
  
  # Health check endpoint
  healthcheckPath = "/api/health"
  
  # Timeout settings
  healthcheckTimeout = 60
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 5

[environments.production]
  # Production environment variables
  NODE_ENV = "production" 